### ISSUE TITLE
where is superadmin function?

### ISSUE THREAD

**Issue by mkdruss** [postfixadmin/postfixadmin#174]
List all available domains for superadmin doesnt work.

[postfixadmin3.1_superadmin.txt](https://github.com/postfixadmin/postfixadmin/files/2008384/postfixadmin3.1_superadmin.txt)

(not much tested patch)

**Comment by cboltz** [comment]
I'm completely surprised that you need such a patch, and I'm quite sure that you are the only one with this problem - otherwise we'd have more than enough bugreports for such a visible problem.

Can you please provide some details about about your problem?

Which PostfixAdmin version do you use?

Was your database created by PostfixAdmin? If it was with an older version, did you run setup.php after the upgrade?

**Comment by mkdruss** [comment]
hmm, changed user name in table admin but not in table domain_admins 
i was confused by admin.superadmin column
sorry
