### ISSUE TITLE
What kind of password encryption try postfix is used

### ISSUE THREAD

**Issue by lilongen1** [postfixadmin/postfixadmin#21]
I wrote a change passwords in the roundcube plug-in, because don't know if postfix is use md5 encryption, so has been not modify the password and the system USES encryption mode matching.
thanks!

**Comment by lilongen1** [comment]
I use this writing plus the {CRAM - MD5}
[b]UPDATE mailbox SET password=CONCAT(\'{CRAM-MD5}\',MD5(%q)) WHERE username=%u LIMIT 1[/b]
But save the string in the database after the new password encryption, namely {CRAM - MD5} behind, or not, because still can't login with new password.
<img src="https://raw.githubusercontent.com/lilongen1/ziluopao/master/roundcube%20question2.png"/>

**Comment by cboltz** [comment]
There's nothing like _the_ encryption scheme.

You can choose which encryption scheme to use in the PostfixAdmin config ($CONF['encrypt']).

That said - I'd recommend not to modify the database manually. It's probably harmless when only changing the password (BTW - do you also update the 'modified' column and write something to the log table?), but it also means your plugin will need quite some code to handle the various encryption schemes.

PostfixAdmin comes with an xmlrpc interface which you might want to use.

**Comment by DavidGoodwin** [comment]
The Squirrelmail plugin for Postfixadmin uses the XMLRPC interface to change the password. That way you don't have to worry about what hashing format is being used. The only downside is that you need to authenticate the end user with the xmlrpc interface - so you will probably need to ask them for their username/password in order to change it.
