### ISSUE TITLE
Disabling password expiration on master branch?

### ISSUE THREAD

**Issue by trippleflux** [postfixadmin/postfixadmin#222]
I am trying to disable password expiration feature on postfixadmin but no matter what i have done, there is always "Pass expires" field when trying to creating new domain, how to completely disable it?.

I have put the following variables but still "Pass expires" field appearing when creating new domain : 
$CONF['password_expiration_enable'] = 'NO';
$CONF['password_expiration'] = 'NO';

I am on postfixadmin vanilla master branch

**Comment by trippleflux** [comment]
Because when enabling password expiration, i am always getting the following when creating new mailbox : 
DEBUG INFORMATION:
Invalid query: Incorrect datetime value: '' for column 'password_expiry' at row 1

Check your error_log for the failed query.

Please check the documentation and website for more information.

**Comment by gizmocuz** [comment]
Same issue here, dropped all tables, did setup again, created first domain, tried to add first mailbox, same error as above
Also on master branch

**Comment by dismasgrp** [comment]
Had the same issue here,  but it is so weird, because the same version of postfixadmin 3.2 works so well in my other server. 

I have the same postfixadmin version 3.2 running on 2 servers.

Server 1: I downloaded postfixadmin 3.2 a couple of months ago on around July 2018 from the master branch.

Server 2: I downloaded postfixadmin 3.2 just yesterday on December 22nd, 2018.

So, I decided to compare both versions...
 
Unfortunately, why there are so many differences in the same versions?? It should have been upped at least to 3.2.1.

Now, the issues mentioned above can be resolved temporarily when you comment the following line of code found on the the model/MailboxHandler.php file it at function initStruct. You need to do the following:

`'password_expiry'  => pacol(0,          0,      1,      'ts',   'password_expiration'`

into 

`#'password_expiry'  => pacol(0,          0,      1,      'ts',   'password_expiration'`

And the mailbox was created.... I understand this is not a fix, but it resolves temporarily and mailbox was created and I could login from Thunderbird, and users are happy (for now).

**Comment by DavidGoodwin** [comment]
You appear to be confusing git branches etc. 

 * **master** (where development takes place, new things appear etc) and a 
 * stable release branch (E.g. **postfixadmin-3.2**).

Download either from https://github.com/postfixadmin/postfixadmin/releases or checkout a specific branch (e.g. postfixadmin-3.2). 

'master' contains shiny new things, which may not all work correctly

**Comment by neuffer** [comment]
Hi David

> You appear to be confusing git branches etc.
> 
>     * **master** (where development takes place, new things appear etc) and a
> 
>     * stable release branch (E.g. **postfixadmin-3.2**).
> [...]
> 'master' contains shiny new things, which may not all work correctly

You are of course right, people easily mistake master for the current release branch.

However I believe it would make sense to roll up all new changes into an official release at bit more often then once every couple of years.

There are so many improvements to PFA between the releases that people do not want to wait this long and per default use the master branch. This causes confusion and problems over and over again since nobody knows off hand which changes are in your installation that you used a copy of master for when you did the last update.

On the other hand it also makes it harder for distributions to keep up-to-date. Ancient packages in Debian and Ubuntu are a prominent example. Package maintainers tend to only track official releases and Debian is about to start the freeze for the next release. With a new release I could prod the developer who's been doing the last uploads to refresh the package in Debian before it gets frozen and you get stuck with an old package and corresponding questions for the next years.
[Buster freeze policy](https://release.debian.org/buster/freeze_policy.html)

Key Debian release dates for Debian 10 (buster):

    [2019-Jan-12] Transition freeze
    [2019-Feb-12] Soft freeze (no new packages, no re-entry, 10-day migrations)
    [2019-Mar-12] Full freeze

Meaning: 
it is easiest to update the package before 20190112, 
From 20190112 to 20190211 an upload may not trigger any issues to be accepted. 
From 20190212 on only small bugfixes are accepted, no new features like we have in in the diff of 3.2 against master. 
From 20190312 on only highly targeted bugfixes for bugs of the severity serious or higher are accepted after manual intervention. The default action for packages with RC bugs is removal from the distribution at this point.



Mike

**Comment by DavidGoodwin** [comment]
@neuffer - yes, you're quite right we don't do releases often enough. (From my own point of view it's probably because I've not done much work on PFA in the last year or so, except from merging a few pull requests and some token bug fixes).

Perhaps it's time to think of 3.3 or something....

**Comment by neuffer** [comment]
On 22.12.18 17:48, David Goodwin wrote:
>
> @neuffer <https://github.com/neuffer> - yes, you're quite right we
> don't do releases often enough. (From my own point of view it's
> probably because I've not done much work on PFA in the last year or
> so, except from merging a few pull requests and some token bug fixes).
>
> Perhaps it's time to think of 3.3 or something....
>

Maybe you personally, from your point of view haven't, but the pull
requests that you two guys have merged already have brought enough
significant changes to justify a new release i believe.

You could also discuss a 3 level version numbering sheme;

<Major>.<Minor>.<2nd lvl minor> 3.2.1
or based on the datamodel change id (but the datamodel has been pretty
stable recently)
<Major>.<Minor>.<Upgrade ID> ie 3.2.1842
or my favorite based on git and the date to make it sortable
<Major>.<Minor>.git<YYYYMMDD>-<GIT commit> ie 3.2.git20181218-18be203
<https://github.com/postfixadmin/postfixadmin/commit/18be20303931530f73c25c971a2833ca0e8198f7>

Cheers
  Mike

**Comment by DavidGoodwin** [comment]
(I was trying to say - as I don't feel I've not spent much time on the project in the last year - it kind of makes me feel that not all that much has changed ... but as you rightly point out, it has ...)

**Comment by dismasgrp** [comment]
Hi @DavidGoodwin, thanks for your update and response. I did not mean any complaints, I am thankful for the software, and yes, you are right, I cloned the postfixadmin from the master branch, thanks for clearing it up. So I needed to reinstall it today. 

Maybe it's just me, but I do not expect Postfixadmin to be updated many times unless they have some features like: 

1) Analytics & Reporting, how many emails were bounced, marked as spam, and delivered for all domains.
2) In the Security Area, such as integrating login with Google Captcha v2 and v3.

How to join the postfix admin developer? I am considering and see if I have time to help.

Thank you!

**Comment by DavidGoodwin** [comment]
@dismasgrp just submit pull requests ... eventually someone will get fed up with merging them and add you ;-)

**Comment by DavidGoodwin** [comment]
I think the password_expiration problem(s) are now fixed on master (at least they seem to be for me...).

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/commit/54cb34cceb68349b65615bfdf10d73e018e25334 - there's a postfixadmin_3.2.1 release/tag in github.
