### ISSUE TITLE
Invalid token!

### ISSUE THREAD

**Issue by neuraload** [postfixadmin/postfixadmin#254]
Hello,

I am facing this error when I try to login with  a fresh installation. Right now I am using the master branch  and its returning the same error. I've tried with stable branches too and its the same.

I have checked the POST data in browser and the sessions on the server and I see this:

Browser:

token: faba7e281fb2969084a484af1f070462
Set-Cookie: postfixadmin_session=78vd4l85ogc5p2r7s3mqm3smjq

Server:
/sess_vgrvb1nfo6bkj1clajbh6srv48:PFA_token|s:32:"faba7e281fb2969084a484af1f070462";

sess_78vd4l85ogc5p2r7s3mqm3smjq

flash|a:0:{}lang|s:2:"ro";

Any toughts ? 

Thank you.

L.E I commented the token check and its working. I think something its wrong with in the code itself.

**Comment by DavidGoodwin** [comment]
To me, it looks like you have two session files ( sess_78vd4l85ogc5p2r7s3mqm3smjq & sess_vgrvb1nfo6bkj1clajbh6srv48 ) on the server which is why it's not working.

Your session can't change between requests - if it does, the CSRF token is lost (the PFA_TOKEN thing).

Is your browser blocking cookies or something?

**Comment by neuraload** [comment]
Hello, 

I have tried with different browsers and its the same ( I am on Mac ). I will test on a Windows environment and see if still complaining about token. Thank you

**Comment by DavidGoodwin** [comment]
See also 
https://github.com/postfixadmin/postfixadmin/commit/f9fd24aecde4ebec8a4b85aa4e25fafc334a60e5

and

#240
