### ISSUE TITLE
Dovecotpw needs to read my TLS certificate and its private key

### ISSUE THREAD

**Issue by AlphaJack** [postfixadmin/postfixadmin#398]
I can't find it documented anywhere and I also don't understand the logic behind this: why does PostfixAdmin need to read my TLS certificate private key to allow login or create users?

Postfix, Dovecot and IMAP clients work well with the default ownership and permissions settings of Let's Encrypt files and folders (probably because their master processes are run as root), however to login on PostfixAdmin or create an account I need to run, as root:

```bash
# replace "postfixadmin" with your php-fpm user group, e.g. "www-data" for Ubuntu

# from root:root
chown root:postfixadmin /etc/letsencrypt/live/example.org/privkey.pem
chown root:postfixadmin /etc/letsencrypt/live
chown root:postfixadmin /etc/letsencrypt/archive

# from 600
chmod 640 /etc/letsencrypt/live/example.org/privkey.pem

# from 700
chmod 750 /etc/letsencrypt/live
chmod 750 /etc/letsencrypt/archive
```

If settings are different from above, when logging in, the page will simply refresh, throwing this vague error in NginX error log:
```
2020/11/28 01:08:46 [error] 534#534: *548 FastCGI sent in stderr: 
"PHP message: PostfixAdmin login failed (username: admin@example.org, ip_address: 127.0.0.1)" 
while reading response header from upstream, client: 127.0.0.1, server: postfixadmin, request: "POST /login.php HTTP/1.0", upstream: "fastcgi://unix:/run/postfixadmin/postfixadmin.sock:", host: "example.org"
```

By creating a new admin from setup.php the error gets more useful:
```
2020/11/28 01:11:36 [error] 534#534: *641 FastCGI sent in stderr: 
"PHP message: dovecotpw password encryption failed. STDERR output: doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 154: ssl_cert: Can't open file /etc/letsencrypt/live/example.org/fullchain.pem: Permission denied"
while reading response header from upstream, client: 127.0.0.1, server: postfixadmin, request: "POST /setup.php HTTP/1.0", upstream: "fastcgi://unix:/run/postfixadmin/postfixadmin.sock:", host: "example.org"
```

By changing ownership and permissions of only the directories /etc/letsencrypt/live and /etc/letsencrypt/archive, the error becomes:
```
2020/11/28 01:14:22 [error] 534#534: *641 FastCGI sent in stderr: 
"PHP message: dovecotpw password encryption failed. STDERR output: doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 154: ssl_key: Can't open file /etc/letsencrypt/live/example.org/privkey.pem: Permission denied"
while reading response header from upstream, client: 127.0.0.1, server: postfixadmin, request: "POST /setup.php HTTP/1.0", upstream: "fastcgi://unix:/run/postfixadmin/postfixadmin.sock:", host: "example.org"
```

**Comment by DavidGoodwin** [comment]
it's an issue with dovecot / doveadm, not technically postfixadmin. Although postfixadmin calls doveadm, which is why you see the problem.

**Comment by DavidGoodwin** [comment]
see also https://github.com/postfixadmin/postfixadmin/issues/379

**Comment by DavidGoodwin** [comment]
see also - https://github.com/postfixadmin/postfixadmin/issues/382 - which probably has a fix

**Comment by AlphaJack** [comment]
Ok, I see, thank you.
Do you have any clue on why `doveadm pw` needs to access dovecot configuration and read some of the files listed there to generate a _simple_ password hash?

**Comment by DavidGoodwin** [comment]
I don't know why; it's a dovecot change.

**Comment by AlphaJack** [comment]
I've reached out Dovecot developers asking if read access in `doveadm pw` is really required, I will post updates when they will reply.

For the auth problem, I see that it goes away with my workaround, but I don't understand why: if PostfixAdmin has direct access to the mail database, why it can't authenticate neither admins nor even regular users? How does the authentication work?

It doesn't seem to use neither an auth socket created by Dovecot, nor the command `doveadm auth` (which would obviously require read access to dovecot.conf)

**Comment by piiskop** [comment]
> I see that it goes away with my workaround

I don't see it:

> chown root:postfixadmin /etc/letsencrypt/live/test.tennis24.ee/privkey.pem 
> chown: vigane grupp: `root:postfixadmin'

There's no such group as _postfixadmin_. And it complains about _fullchain.pem_:

> [Wed Dec 02 16:08:15.393508 2020] [php7:notice] [pid 1636] [client 192.168.1.65:48922] STDERR output: doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 13: ssl_cert: Can't open file /etc/letsencrypt/live/test.tennis24.ee/fullchain.pem: Permission denied\n, referer: https://postfixadmin.tennis24.ee/setup.php

**Comment by AlphaJack** [comment]
You should use the main group of the user running the php-fpm pool for PostfixAdmin. Another way (not reccomended) is to make the file world readable via `chmod +r`.

The group name depends on your system, it may be "www-data" in Ubuntu, the package in Arch Linux repos creates the specific user "postfixadmin" for this task.

You could test it even with your normal user: if you don't have read access to /etc/dovecot/dovecot.conf and you run `doveadm pw -p XXXXXX`, you get an error:

```
doveconf: Fatal: open(/etc/dovecot/dovecot.conf) failed: Permission denied (copy example configs from /usr/share/doc/dovecot/example-config/)
```

If you are able to read dovecot.conf with your normal user, you get a similar error for other files you aren't allowed to read (as you already saw):

```
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 155: ssl_cert: Can't open file /etc/letsencrypt/live/example.org/fullchain.pem: Permission denied
```

For instance, if you specified a [dhparam file](https://wiki.dovecot.org/SSL/DovecotConfiguration#SSL_security_settings), you need to read it as well to create a password hash through `doveadm`.
I am absolutely not an expert here, but the program seems to require more than it needs to launch the function `pw`

**Comment by DavidGoodwin** [comment]
1. Login is failing because you've configured Postfixadmin to use dovecot for it's hashing mechanism.
 2. Check the value of 'encrypt' within config.local.php (or config.inc.php). I assume yours is dovecot:<something>
 3. I don't know what's in your database, but it may be possible to change to a different hash backend (e.g. from dovecot:sha256 to php_crypt:SHA256

**Comment by piiskop** [comment]
> 2\. Check the value of 'encrypt' within config.local.php (or config.inc.php). I assume yours is dovecot:

$CONF['encrypt'] = 'dovecot:ARGON2I';

**Comment by piiskop** [comment]
> 3\. change to a different hash backend (e.g. from dovecot:sha256 to php_crypt:SHA256

After the change and restart of _apache2_:

> [Wed Dec 02 16:45:26.615145 2020] [authz_core:debug] [pid 28110] mod_authz_core.c(809): [client 192.168.1.65:49412] AH01626: authorization result of Require all granted: granted, referer: https://postfixadmin.tennis24.ee/setup.php
> [Wed Dec 02 16:45:26.615186 2020] [authz_core:debug] [pid 28110] mod_authz_core.c(809): [client 192.168.1.65:49412] AH01626: authorization result of <RequireAny>: granted, referer: https://postfixadmin.tennis24.ee/setup.php
> [Wed Dec 02 16:45:26.627731 2020] [php7:warn] [pid 28110] [client 192.168.1.65:49412] PHP Warning:  Cannot assign an empty string to a string offset in /usr/share/postfixadmin/variables.inc.php on line 31, referer: https://postfixadmin.tennis24.ee/setup.php
> [Wed Dec 02 16:45:26.728127 2020] [deflate:debug] [pid 28110] mod_deflate.c(854): [client 192.168.1.65:49412] AH01384: Zlib: Compressed 1314 to 730 : URL /setup.php, referer: https://postfixadmin.tennis24.ee/setup.php

**Comment by piiskop** [comment]
> You should use the main group of the user running the php-fpm pool for PostfixAdmin.

Well, I did it:

> root@test:/etc/letsencrypt/live/test.tennis24.ee# chown root:www-data /etc/letsencrypt/live/test.tennis24.ee/fullchain.pem 
> root@test:/etc/letsencrypt/live/test.tennis24.ee# l -la
> kokku 12
> drwxr-xr-x  2 root root     4096 dets   2 02:33 ./
> drwxr-x--- 10 root www-data 4096 juuli  6 17:03 ../
> lrwxrwxrwx  1 root root       40 dets   2 02:33 cert.pem -> ../../archive/test.tennis24.ee/cert4.pem
> lrwxrwxrwx  1 root root       41 dets   2 02:33 chain.pem -> ../../archive/test.tennis24.ee/chain4.pem
> lrwxrwxrwx  1 root root       45 dets   2 02:33 fullchain.pem -> ../../archive/test.tennis24.ee/fullchain4.pem
> lrwxrwxrwx  1 root root       43 dets   2 02:33 privkey.pem -> ../../archive/test.tennis24.ee/privkey4.pem
> -rw-r--r--  1 root root      682 juuni 26 14:24 README

As you see, the system doesn't change the group for these files.

Meanwhile, checking for new messages to kalmer@test.tennis24.ee, I get an error message in _Thunderbird_ for having an incorrect authentication method which is _normal password_.

**Comment by AlphaJack** [comment]
They appear world readable because they are links, however the real file permission could (and probably are different). 

By running that command directed to `/etc/letsencrypt/live/test.tennis24.ee/fullchain.pem` you have changed the permissions of `/etc/letsencrypt/archive/test.tennis24.ee/fullchain.pem`. 

You should then check directory permissions, because even if the right files are accessible to the correct group, they may still be located behind inaccessible folders:
- /etc should be 755
- /etc/letsencrypt should be 755
- /etc/letsencrypt/live could be 700, change it. Same for archive
- /etc/letsencrypt/live/example.org should be 755. Same for archive

Once you modified the permissions correctly, you should see the following inside /etc/letsencrypt/archive/example.org
```
-rw-r--r-- 1 root root 1.9K Nov 26 22:02 cert1.pem
-rw-r--r-- 1 root root 1.7K Nov 26 22:02 chain1.pem
-rw-r--r-- 1 root root 3.5K Nov 26 22:02 fullchain1.pem
-rw------- 1 root root 1.7K Nov 26 22:02 privkey1.pem
```
The only file that returns problem now is privkey1.pem, that you could either
- chown root:www-data AND chmod 640
- chmod 644 (not suggested)

Remember that folders need the execution permission, so you want 750 instead of 640 for a folder accessible by both owner and group. 
Note that if the files are still 600 it means that the group www-data has still no access to them (even if they are owned by that group), you need at least 640.

**Comment by piiskop** [comment]
My file permissions seem to be suitable according to your suggestions:

- root@test:/# l -la /etc/letsencrypt/archive/test.tennis24.ee/
- kokku 72
- drwxr-xr-x  2 root root     4096 dets   2 02:33 ./
- drwxr-x--- 10 root www-data 4096 juuli  6 17:03 ../
- -rw-r--r--  1 root root     1915 juuni 26 14:24 cert1.pem
- -rw-r--r--  1 root root     1915 aug   25 13:31 cert2.pem
- -rw-r--r--  1 root root     1915 okt   24 23:16 cert3.pem
- -rw-r--r--  1 root root     1911 dets   2 02:33 cert4.pem
- -rw-r--r--  1 root root     1647 juuni 26 14:24 chain1.pem
- -rw-r--r--  1 root root     1647 aug   25 13:31 chain2.pem
- -rw-r--r--  1 root root     1647 okt   24 23:16 chain3.pem
- -rw-r--r--  1 root root     1647 dets   2 02:33 chain4.pem
- -rw-r--r--  1 root root     3562 juuni 26 14:24 fullchain1.pem
- -rw-r--r--  1 root root     3562 aug   25 13:31 fullchain2.pem
- -rw-r--r--  1 root root     3562 okt   24 23:16 fullchain3.pem
- -rw-r-----  1 root www-data 3558 dets   2 02:33 fullchain4.pem
- -rw-r--r--  1 root root     1704 juuni 26 14:24 privkey1.pem
- -rw-r--r--  1 root root     1704 aug   25 13:31 privkey2.pem
- -rw-r--r--  1 root root     1704 okt   24 23:16 privkey3.pem
- -rw-r-----  1 root www-data 1704 dets   2 02:33 privkey4.pem
- root@test:/# l -la /etc/letsencrypt/live/test.tennis24.ee/
- kokku 12
- drwxr-xr-x  2 root root     4096 dets   2 02:33 ./
- drwxr-x--- 10 root www-data 4096 juuli  6 17:03 ../
- lrwxrwxrwx  1 root root       40 dets   2 02:33 cert.pem -> ../../archive/test.tennis24.ee/cert4.pem
- lrwxrwxrwx  1 root root       41 dets   2 02:33 chain.pem -> ../../archive/test.tennis24.ee/chain4.pem
- lrwxrwxrwx  1 root root       45 dets   2 02:33 fullchain.pem -> ../../archive/test.tennis24.ee/fullchain4.pem
- lrwxrwxrwx  1 root root       43 dets   2 02:33 privkey.pem -> ../../archive/test.tennis24.ee/privkey4.pem
- -rw-r--r--  1 root root      682 juuni 26 14:24 README

Meanwhile, I was able to make kalmer@test.tennis24.ee to receive messages from outside by opening the port _25_ for public. Currently, I have the following ports open for public: _22_, _25_, _80_, _143_, _443_ and _587_. Do I need some other ports to be open for public? Can that be connected to the issue that _postfixadmin_ can't let me in because _dovecot_ fails to read _fullchain.pem_?

**Comment by AlphaJack** [comment]
Files seems good, if you run `sudo -u www-data nano /etc/letsencrypt/live/test.tennis24.ee/privkey.pem` and `sudo -u www-data nano /etc/letsencrypt/live/test.tennis24.ee/fullchain.pem` are you able to read the files?

Note that Postfix and Dovecot can work well even if PostfixAdmin isn't working (or installed at all)

> Do I need some other ports to be open for public? Can that be connected to the issue that postfixadmin can't let me in because dovecot fails to read fullchain.pem?

I don't think so. The ports I use for mail are:
- 25 (SMTP): required to receive emails from others. No way you can assign a different port to this task
- 465 (submissionS): send mail using Postfix. You use 587 (submission) for that, it's fine.
- 993 (IMAPS): access my inbox using Dovecot. You use 143 (IMAP) for that, I disabled it and switched to full encryption only.

---

> It complains about missing ssl_dh. I have no idea what that is.


Check out the [link](https://wiki.dovecot.org/SSL/DovecotConfiguration#SSL_security_settings) I sent before regarding Diffie-Hellman parameters:

> For instance, if you specified a dhparam file, you need to read it as well to create a password hash through doveadm.

I don't have anymore that option, but I use

```
ssl_min_protocol = TLSv1.2
```

**Comment by AlphaJack** [comment]
Still no reply from Dovecot devs

**Comment by joh-ku** [comment]
Applying different permissions to key files is imho never a good solution.

It is possible to workaround this issue. Create a file e.g. `ssl-keys.conf` and move the `ssl_key` and `ssl_cert` keys of `dovecot` (normally in `10-ssl.conf`) into this file. Give the newly created file permission `600` and set as owner `root`.

Then include this file in your `dovecot.conf` with this line `!include_try ssl-keys.conf`.

Restart `dovecot` and you should be able to call `doveadm pw` with a non-privileged user like e.g. `www-data`.

See [this discussion](https://dovecot.org/pipermail/dovecot/2020-August/119646.html) for further reference.

**Comment by AlphaJack** [comment]
> Applying different permissions to key files is imho never a good solution.

I knowm but I'd rather revoke those permissions whenever I don't need the postfixadmin (www-data) user to read my private TLS key (99.99% of the times, and it shouldn't be required in the first place even for that 0.01%).

**Comment by DavidGoodwin** [comment]
see also : https://github.com/postfixadmin/postfixadmin/pull/491 - probably needs rewriting again - but hopefully there's a solution in the making

**Comment by joh-ku** [comment]
> I knowm but I'd rather revoke those permissions whenever I don't need the postfixadmin (www-data) user to read my private TLS key (99.99% of the times, and it shouldn't be required in the first place even for that 0.01%).

The `postfixadmin` user does not need to read your key. The error message is displayed depending on your [dovecot configuration](https://doc.dovecot.org/configuration_manual/config_file/?highlight=include_try#including-config-files). That's why I commented [above](https://github.com/postfixadmin/postfixadmin/issues/398#issuecomment-843124406). You can leave those permissions untouched.

> see also : #491 - probably needs rewriting again - but hopefully there's a solution in the making

Good to know, thanks!

**Comment by AlphaJack** [comment]
Ok, I see, I can move secrets away from the main dovecot.conf using !include_try and strict permissions, and then make dovecot.conf world readable in order to get `doveadm` to work.
Thanks!

**Comment by mulderij** [comment]
An alternative is through php_crypt and then modify the Dovecot password query against MariaDB.

*/etc/postfixadmin/config.local.php*
```
$CONF['encrypt'] = 'php_crypt:SHA512';
```
*/etc/dovecot/dovecot-sql.conf.ext*
```
password_query = \
  SELECT \
  CASE \
    WHEN LEFT(password,4) = '$2y$' THEN CONCAT('{CRYPT}', password) \
    WHEN LEFT(password,3) = '$6$' THEN CONCAT('{SHA512-CRYPT}', password) \
    WHEN LEFT(password,3) = '$5$' THEN CONCAT('{SHA256-CRYPT}', password) \
    WHEN LEFT(password,3) = '$1$' THEN CONCAT('{MD5-CRYPT}', password) \
  END AS password \
  FROM mailbox \
  WHERE username='%u'
```
This doesn't add the the string for the encryption method in the database, but adds it in the result returned to Dovecot. For some unclear reason Dovecot needs this (the $\<code>$ should have been enough). Of course if you are only using sha512 not all rewrite cases are necessary, but they don't hurt...

**Comment by mvasi90** [comment]
I really don't understand people. I'm reading the comments, and I see the people are juggling with system permissions and the security. 

· Having read permissions for others in dovecot configuration files allows anyone to read database passwords and other sensitive configuration. My `/etc/dovecot/` files permissions are `0640`.
`doveadm pw` is not running at all with an unprivileged user other than `dovecot` because it needs access to `/run/dovecot`, `/etc/dovecot/`, `/etc/letsencrypt/`, etc.
 Nobody understands why the `pw` command reads the ssl certs/keys and the configuration files.

· Adding the `dovecot` group to the `postfixadmin` or `www-data` user is giving away access to anyone who finds a vulnerability in the web service, to the entire dovecot configuration, including certificates and ssl keys.

This issue was created 4 years ago. The stable version 3.3.13 (as of 2024-01-28) still has no native solution for `doveadm pw` (argon2id) hashes.

I don't want a new and maybe unstable master branch on my system. Then, to solve this problem I created a small bash script that emulates the behavior of the `doveadm pw` with the following differences:

· It does not need any special access to any file, because it does not read any file.
· It works without root privileges.
· It uses native `argon2` tool for creating and verifying the hash.


Here is the source code.
I do not want any kind of recognition or mention of my name. I am not one of those who want to see their name on fences when walking down the streets.

```bash
#!/bin/bash

# This script emulates the behavior of "doveadm pw". You can use it on PostfixAdmin
# for generating and checking argon2 hashes natively.
#
# The latest version of Dovecot requires access to /etc/dovecot/,
# /run/dovecot and /etc/letsencrypt/ when running "doveadm pw" 
#
# Run doveadm pw is impossible without changing permissions to all the above files/folders
# or adding the dovecot group to the postifxadmin user. This is a security risk.
#
# To solve that without breaking the security use this script.
#
# 1. Copy this script to /usr/local/bin and set execution permission 0755.
# 2. Edit the file /etc/webapps/postfixadmin/config.local.php and insert the next line:
#
# $CONF['dovecotpw'] = '/usr/local/bin/postfixadmin-pw';
#
# That's all.
#
# Author: nobody
# Copyright = Copyleft = Copyup = Copydown = Copymadafaka
# You can do what do you want. It's your code. No mentions, no names on walls.

if [[ "$(stat -c "%a" "$0")" != "755" ]]; then
  >&2 echo "Wrong file permissions. Must be 0755"
  exit
fi

if [[ -p /dev/stdin ]]; then
  IFS= read -r pass
  if [[ "${4}" == {ARGON2ID}* ]]; then
    v="$(echo -n ${4} | sed 's/.*v=\([0-9]\+\).*/\1/')"
    v=$(printf "%x" $v) # version in hex (19 = 0x13)
    m="$(echo -n ${4} | sed 's/.*m=\([0-9]\+\).*/\1/')"
    t="$(echo -n ${4} | sed 's/.*t=\([0-9]\+\).*/\1/')"
    p="$(echo -n ${4} | sed 's/.*p=\([0-9]\+\).*/\1/')"
    salt="$(echo -n ${4} | sed 's/.*\$\([^$]\+\)$.*/\1/')"
    pass_hash="$(echo -n ${4} | sed 's/.*\$.*\$\(.*\).*/\1/')"
    salt_padding=$((4- ${#salt} % 4))
    [[ $salt_padding -gt 0 ]] &&  [[ $salt_padding -lt 4 ]] && salt+="$(printf "=%.0s" $(seq 1 $salt_padding))"
    salt=$(echo -n "$salt" | base64 -d)
    new_hash=$(echo -n "$pass" | echo "{ARGON2ID}$(/usr/bin/argon2 "$salt" -id -k $m -t $t -p $p -e -v $v -l 32)")
    new_pass_hash="$(echo -n "$new_hash" | sed 's/.*\$.*\$\(.*\).*/\1/')"
    [[ "$pass_hash" = "$new_pass_hash" ]] && echo "$new_hash (verified)" || echo "Fatal: reverse password verification check failed: Password mismatch"
  else
    echo -n "$pass" | echo "{ARGON2ID}$(/usr/bin/argon2 $(openssl rand -hex 8) -id -k 65536 -t 3 -p 1 -e -v 13 -l 32)"
  fi

else
  >&2 echo "Missing password"
fi
```

Have a nice life!

**Comment by DavidGoodwin** [comment]
thanks @mvasi90

**Comment by Icel3lade** [comment]
> I really don't understand people. I'm reading the comments, and I see the people are juggling with system permissions and the security.
> 
> ```

My Hero! 👍 Completely agree, thank you so much!

**Comment by bevice** [comment]
$CONF['dovecotpw'] = '/usr/local/bin/doveadm-pw';

```# cat /etc/sudoers.d/doveadm-pw```

    ALL ALL=(root) NOPASSWD: /usr/bin/doveadm pw *

```# cat /usr/local/bin/doveadm-pw```

    sudo /usr/bin/doveadm pw "$@"
