### ISSUE TITLE
horrible new look 

### ISSUE THREAD

**Issue by nerozero** [postfixadmin/postfixadmin#533]
Why all buttons are so huge ? Bigger does not mean better.
The top empty space is almost 1/4 of my screen. What is the point ?
On old interface I could see entire staff  on one page, now i cant see even a half of them, and I have 2k screen!

Literally my hart is crying.

**Comment by DavidGoodwin** [comment]
I take you're not a fan of bootstrap then ? :) 

Any chance of some screenshots with squiggly lines/annotations to highlight the bits you don't like ... ?

**Comment by nerozero** [comment]
DavidGoodwin, Thank you for reply.

I have rolled back the update immediately so now i'm on previous version. (My bad, I should have been created a screenshots... sorry)
Please let me share my feelings hypertrophying on almost everywhere now days. This project is to me one of the most important tool for administering a lots of mail servers. For my perspective - less free space / more visible information on single page is appreciated. 

KISS - Keep It Simple and Stupid. 
Dont follow Micro$oft approach - make everything huge and bloated with useless staff. You had already good web interface. Keep your personality. 

Thanks for maintaining this project!

**Comment by volker-raschek** [comment]
I can only agree with this. We are in the process of migrating postfixadmin to kubernetes and will not roll out the new version so that employees can use it to configure their mailbox or subdomain admins can manage their domains.

I think it's great that Bootstrap is used here, but the realization of the style guide is a disaster.

**Comment by volker-raschek** [comment]
Hi @DavidGoodwin,

> Any chance of some screenshots with squiggly lines/annotations to highlight the bits you don't like ... ?

I think the padding and margin settings are to large. Here are some screenshots. My desktop resolution is 1980x1080p.

[Bildschirmfoto vom 2021-09-10 21-38-28](https://user-images.githubusercontent.com/18311012/132908894-625ad940-0c0d-4e3e-9722-4325934721e4.png)
[Bildschirmfoto vom 2021-09-10 21-38-50](https://user-images.githubusercontent.com/18311012/132908897-dc74ddb5-f0c6-4633-b9ce-4675461e973f.png)
[Bildschirmfoto vom 2021-09-10 21-39-19](https://user-images.githubusercontent.com/18311012/132908898-c512a225-bf09-422a-9242-e918c5ad68e6.png)

**Comment by DavidGoodwin** [comment]
So .... from my point of view, if someone wants to dig out the old theme from git history, and re-add it so it's somehow trivially easy to choose to use the old theme, then fine.... submit a PR and I'll merge it.  

I don't remember any comments or negative feedback on the bootstrap theme when it was added/merged, and it's been quite some time since this happened ( https://github.com/postfixadmin/postfixadmin/pull/172 ) .....

**Comment by tbsky** [comment]
I know it is too late. I was using 3.2.4 due to old php version and 3.2.4 works fine for me.
today I upgrade to 3.3.11 and found this colorful bootstrap theme.
it really is beautiful eye candy I think. then I try to edit the config to change back to the old theme.. and surprise!!
there is no more old theme. 
as an administrator I love old theme which seems ugly but actually easier to do the job. but I think that's history and I need to live with it now.
