### ISSUE TITLE
DEBIAN 10 / PHP7.4

### ISSUE THREAD

**Issue by cpnadal** [postfixadmin/postfixadmin#588]
hello, I have the issue once login on the latest version.

Invalid token (session timeout; refresh the page and try again?)

I read and try almost all solutions offered but no one work.

Timezone are ok in mysql/php/system

i really don't understand what happens.

Could someone help me?

Many thanks in advance

**Comment by damnms** [comment]
paste logs - everything else is just guessing

**Comment by DavidGoodwin** [comment]
Hi - Sorry - I must have missed the email alert for this ....

If there's some sort of session timeout type thing happening, it's probably pointing to a problem with cookies somehow.

The most obvious problem is where the server isn't able to maintain state (i.e. PHP's session support is broken, perhaps because of file permission problems on the server), or for some reason your browser is blocking cookies.
