### ISSUE TITLE
RegEx-Filter for Internationalized Domain Name

### ISSUE THREAD

**Issue by Cantibra** [postfixadmin/postfixadmin#615]
Hello,

is it possible to adjust the RegEx filter to support the Internationalized Domain Name standard?
For example that domains with german umlauts are workable.

Best regards

**Comment by DavidGoodwin** [comment]
This is similar to the #47 ? 

(having unicode in domain names)

I don't have enough experience handling internationalised domain names to be able to say anything useful.

**Comment by pixil98** [comment]
I just ran into this problem today in a brand new deployment. It seems like postfix is looking up the UTF8 version in the database, not finding a match, and bouncing the email. This only happens with clients that use UTF8 to encode the address during transmission, if I use a client that sends it as punycode then it delivers fine. Sadly Gmail is using UTF8 so any email originating from gmail is bounced.

**Comment by pixil98** [comment]
I did some further research today. According to Postfix, in order to support UTF8 domains, you have to build both out in the lists it's using to source data from. As far as I can tell, this means we need to be able to add both versions in postfixadmin to properly support them.

https://www.postfix.org/SMTPUTF8_README.html#limitations
