### ISSUE TITLE
bug for Expiration Script

### ISSUE THREAD

**Issue by jumecittu** [postfixadmin/postfixadmin#619]
Hello, 

Expiration Script it could be potentially malicious. If launched with higher privileges it allows an escalation to privileged user.  I'm available for any clarification.

**Comment by DavidGoodwin** [comment]
@jumecittu happy with the above?

**Comment by jumecittu** [comment]
@DavidGoodwin great mod man ! Tnx :-)

**Comment by cboltz** [comment]
Minor nitpicking: Please add quotes around _all_ variables, even if you think they are superfluous ;-) (that is, around $RESULT[..] in lines 94 and 95, and around $REPLY_ADDRESS in line 100)

(Quoting all variables also stops command injection AFAIK - but having the mail address validation can't hurt.)

Probably even better: You could also use `while IFS=$'\t' read EMAIL_TO PASSWORD_EXPIRE GARBAGE ; do` to simplify variable assignment. The `GARBAGE` part is optional, but makes sure that - should there be more fields in the result (unlikely) - they won't end up as part of `PASSWORD_EXPIRE`

With that changed / everything quoted, I doubt that there's still a way left to get a command executed (@jumecittu please correct me if I'm wrong!). That also means that the warning is probably not needed - but please at least keep the "don't run this as root" advice, because that's _always_ a good advise ;-)

As a not-too-related sidenote: I just opened #640 ;-)
