### ISSUE TITLE
imap insecure, what is the alternative?

### ISSUE THREAD

**Issue by kartagis** [postfixadmin/postfixadmin#656]
Hi,

imap for php-fpm is nowhere to be found for Centos Stream, then I was told it was insecure, but we need it to be able to automate the folder creation. Can you suggest an alternative?

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/blob/master/config.inc.php#L617 ?

**Comment by DavidGoodwin** [comment]
I assume you could just create the folder structure manually (using mkdir etc), if the mail folders are hosted locally; otherwise you need to find some way to talk to the imap server and create the folders.

https://www.php-imap.com/api/client looks like it works for PHP without a requirement for the php imap extension.

**Comment by cboltz** [comment]
Just wondering - would pointing people to https://doc.dovecot.org/configuration_manual/namespace/#mailbox-settings be good enough? (If yes, we could simply drop the "create folders" feature. No need to re-invent something that dovecot can do itsself.)

Yes, I know that dovecot is not the only imap server out there, but nowadays it seems like everybody uses it ;-)

**Comment by kartagis** [comment]
IMO yes, because the line https://github.com/postfixadmin/postfixadmin/blob/master/config.inc.php#L617 is so confusing at a glance.

**Comment by DavidGoodwin** [comment]
@kartagis what's confusing about it?

**Comment by kartagis** [comment]
If you hadn't detailed what to do (which I just saw), I wouldn't have known what to do.
