### ISSUE TITLE
Syntax error or access violation: 1091 Can't DROP

### ISSUE THREAD

**Issue by qcybb** [postfixadmin/postfixadmin#693]
Still getting MySQL errors with the latest 3.3.13 version :

```
Exception message: DEBUG INFORMATION: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'vacation_notification_pkey'; check that column/key exists
Check your error_log for the failed query - check logs!
```

Error log :

```
[08-Dec-2022 18:34:24 America/Vancouver] Invalid query: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'vacation_notification_pkey'; check that column/key exists caused by ALTER TABLE `vacation_notification` DROP FOREIGN KEY vacation_notification_pkey
```

**Comment by DavidGoodwin** [comment]
Hi @qcybb - I think I need to improve the github actions / test environment ! 

 * What version of MySQL / MariaDB are you using?
 * Is it possible some previous incomplete update has removed the column - so could you edit upgrade.php and comment out the line that's trying to drop the constraint ?

**Comment by qcybb** [comment]
I'm using MySQL v5.7.40

That seems to have fixed the issue :

```
Updating database:

- old version: 1845; target version: 1847

(If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)
updating to version 1846 (MySQL)...   done

updating to version 1847 (MySQL)...   done
```

**Comment by RSoSIT** [comment]
I had the same problem updating Debian 10 to 12. I don't know where the problem came from, but the FOREIGN KEY had a different name (_ibfk_1 instead of _pkey):

`CONSTRAINT `vacation_notification_ibfk_1` FOREIGN KEY (`on_vacation`) REFERENCES `vacation` (`email`) ON DELETE CASCADE`

Omitting the DROP statement did not help, because there still was a FOREIGN key configured and one of the next steps failed, because of it:

```
ALTER TABLE vacation MODIFY email varchar(255)  COLLATE latin1_general_ci NOT NULL;
ERROR 1833 (HY000): Cannot change column 'email': used in a foreign key constraint 'vacation_notification_ibfk_1' of table 'postfix.vacation_notification'

```
I did the upgrade from DB version 1845 to 1846 manually (do not forget to update the config table with the new version number), using the given key name and then everything worked like a charm.
