### ISSUE TITLE
Please, change default charset of the tables (utf8mb4?)

### ISSUE THREAD

**Issue by quicktrick** [postfixadmin/postfixadmin#76]
Now we have latin1_swedish_ci, it's not very good.

ALTER TABLE table CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci

https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci

**Comment by cboltz** [comment]
There's a reason why we still use latin1 on fields that can only contain ascii chars (like mail address or domain).

MySQL has a limit on the index length (767 bytes).

Why do I mention that?
* with latin1 encoding, each char is one byte.
* with utf8 encoding, each char is 3 bytes
* with utf8mb4 encoding, each char is 4 bytes

We use varchar(255) for most fields, and that means:
* if we need an index covering more than one column, those columns *must* be latin1 so that the index can span up to 3 columns
* an utf8 varchar(255) (3 * 255 = 765 bytes) exactly fits into the allowed index length
* an utf8mb4 varchar(255) (4 * 255 = 1020) is too big for being indexed - we'd have to limit the index to 3/4 of the field length, and this is obviously a bad idea if it needs to be an UNIQUE index ;-)

So - if this was just a general request because utf8mb4 is cool, please understand that we won't do that.

If you noticed a specific field that needs to be changed to utf8 or even utf8mb4, please tell us which table/field needs to change, and we'll probably change/fix it ;-)

**Comment by quicktrick** [comment]
Thanks for the explanation, Christian.
