### ISSUE TITLE
Rouncube does not send emails, error 220 SMTP authorization

### ISSUE THREAD

**Issue by sovkutsan** [postfixadmin/postfixadmin#777]
Hi
My Rouncube does not send emails, error 220 authorization doesn't work...
This was an error before, but then my email used self-signed certificates.
Now I'm using a Lets' Encrypt certificate and still I can't send an email.

Incoming letters arrive (authorization is the same for incoming and outgoing)
Everything works in the Thunderbird email client.

But Roundcube can't send the letter.....

I don’t know what settings to change and what to do if everywhere
mail is working

help me please

**Comment by DavidGoodwin** [comment]
Hi - Your problem is probably with RoundCube talking to Postfix, and there potentially being some sort of password synchronisation issue - or postfix doesn't know to trust your roundcube server.

You need to look at your postfix mail logs (perhaps: /var/log/mail.log, or `journalctl -f`) to get a better error message and to start trying to figure out what's going on.
