### ISSUE TITLE
Migrate away from PHP's imap extension?

### ISSUE THREAD

**Issue by orlitzky** [postfixadmin/postfixadmin#812]
The PHP _imap_ extension is being dumped:

* https://github.com/php/php-src/pull/13190
* https://wiki.php.net/rfc/unbundle_imap_pspell_oci8

The "c-client" library that it's based on hasn't been maintained in 20 years, and is a patch monster on all modern systems. This is just a heads up that the PECL extension will probably deteriorate and become unusable soon, since (speaking as one distro maintainer) we were only bothering to keep it alive because it was a dependency of PHP itself.

**Comment by DavidGoodwin** [comment]
Thanks for the notification.

The 'imap' extension is an optional requirement for postfixadmin, and it's only used if someone has configured various config things (create_mailbox_subdirs, create_mailbox_subdirs_host etc) and the function imap_open exists 

See also 

https://github.com/postfixadmin/postfixadmin/blob/master/model/MailboxHandler.php#L750

and 

https://github.com/postfixadmin/postfixadmin/blob/master/config.inc.php#L703

and 

https://github.com/postfixadmin/postfixadmin/issues/472


I suspect it's time to just remove this code.

**Comment by orlitzky** [comment]
Works for me, I'll let our PostfixAdmin maintainer know. Thank you!

**Comment by hydrapolic** [comment]
Hey @DavidGoodwin, thanks for the update!

Just noticed it's not included in the current release 3.3.14, maybe because this got merged into the master branch and there is a huge diff between master and the 3.3 branch https://github.com/postfixadmin/postfixadmin/compare/postfixadmin_3.3...master

Any plans on merging the branches so that the next release contains this change?

In Gentoo Linux, we're working on getting php 8.4 on board, but we somehow need to solve the issue with the imap extension and postfixadmin compatibility. Currently we state that postfixadmin requires php with imap extension, but it's not included in php 8.4 so there's a small glitch that I was hoping will be fixed in the latest release. Thanks!

**Comment by Uzume** [comment]
It should be noted that the `c-client` library _**is**_ maintained as a part of [Alpine](https://alpineapp.email/) and has been maintained there (as has all of [imap](https://repo.or.cz/alpine.git/tree/refs/heads/master:/imap) that was once part of `uw-imap`) since Alpine integrated [panda-imap](https://github.com/jonabbey/panda-imap) (a fork of UW IMAP by Mark Crispin the original author of `c-client`) on 2013-11-02 (at Alpine 2.19.1; it is also mentioned in the release notes on their website for Alpine 2.20).

It was only ever unmaintained at older locations but Mark Crispin continued to develop it after his time at University of Washington (as [Panda IMAP](https://web.archive.org/web/20120716203757/http://panda.com/imap/)) and Eduardo Chappa continuing its development as a part of Alpine since [Alpine 2.19.1+ since 2013-11-02](https://repo.or.cz/alpine.git/commit/7fe712882b909931088a318c08041b0e7974a000) after Crispin's death at the end of 2012.

Remember Crispin originally developed `c-client` at Stanford University (along with `base64`, etc.) and Crispin and his team developed `pine` and later `alpine` email clients at University of Washington (along with many other things like the their `imapd` server, etc.).

There is even a GH mirror at [alpinemail/alpine](https://github.com/alpinemail/alpine) and anyone looking for a maintained version of `uw-map` should probably look there or at the source repo on `repo.or.cz`. Feel free to compare:
- [uw-imap/imap](https://github.com/uw-imap/imap)
- [jonabbey/panda-imap](https://github.com/jonabbey/panda-imap)
- [alpinemail/imap](https://github.com/alpinemail/alpine/tree/master/imap)

**Comment by orlitzky** [comment]
The PHP extension itself is now unsupported, making it somewhat of a moot point: https://github.com/php/pecl-mail-imap

> This extension is no longer actively maintained or supported, and this repository serves as an archive for it.

Though there may still be distros willing to support it. I'm using it for davical authentication at work, but I plan to replace it with something in pure PHP rather than try to keep the C extension going.

**Comment by Uzume** [comment]
> The PHP extension itself is now unsupported, making it somewhat of a moot point[...]

Yes, the extension was unbundled and subsequently left unsupported. My point was only to state that the `c-client` library is still maintained (along with all of the "imap" distribution that is known to have been in `uw-imap`, e.g., `imapd`, etc.) as a vendored part of the `alpine` email client. This refutes the statement at the top of this issue. "imap" has never really been unmaintained for any extended period (perhaps the longest was 2012–2013, around the time the original author died). That cannot be said of the `php-imap` extension which has had minimal compilation maintenance for a very long time (i.e., none of the updated `c-client` changes were ever pulled in after `uw-imap`).

**Comment by shangjiaxuan** [comment]
I've been using these functionalities on my server for 7/8 years. When I migrated my system from `CentOS 7` to `Rocky 9`, I was having problem making this work. Luckily I found a remi repo version that enables this, and continued. Sadly I don't know how long this will last...
