### ISSUE TITLE
"The alias does not exist" error isn't too helpful (missing alias for mailbox, caused by using PFA with "foreign" database)

### ISSUE THREAD

**Issue by jsknto** [postfixadmin/postfixadmin#88]
Hello, trying to setup the password validation to require at least one digit, this is the configuration:

```
$CONF['password_validation'] = array(
# '/regular expression/' => '$PALANG key (optional: + parameter)',
     '/.{5}/'                => 'password_too_short 5',      # minimum length 5 characters
     '/([a-zA-Z].*){3}/'     => 'password_no_characters 3',  # must contain at least 3 characters
     '/([0-9].*){1}/'        => 'password_no_digits 1',      # must contain at least 1 digits
);
```

- When I try to set any password with one or more digits I receive the message:
**This alias does not exist!**

- When I try to set any password with NO digits I receive the message:
**Your password must contain at least 1 digit(s).** _(which It's Ok)_

If I set the number of digits to 2 or greater, it works fine.

Thanks

**Comment by DavidGoodwin** [comment]
To see: ```This alias does not exist!``` would imply the translation(s) aren't right?

**Comment by jsknto** [comment]
But the password remains unchanged.
Thank you

**Comment by jsfan** [comment]
I am experiencing the same.  Any valid edit to a mailbox will lead to this warning. I recently upgraded from v2.3.4 to v3.1 and manually copied the configuration variable-by-variable to the new configuration file. I also upgraded Postfix and Dovecot at the same time.

In the old version, I can edit the mailboxes and in the new version everything is at least displayed correctly. I can also create new mailboxes.

I doubt that there is an issue with the translations. This is the translation for `alias_does_not_exist` which is only referenced in `AliasHandler.php` .

**Comment by cboltz** [comment]
There is (or at least should be) an alias for every mailbox, even if it only says `user@example.com -> user@example.com` to deliver to the `user@example.com` mailbox.

Can you please check your database if the alias for the mailbox triggering this error exists?

**Comment by jsfan** [comment]
I seem to have aliases for some mailboxes but not for all of them. By the looks of it, it's the oldest ones which do not have an alias. They may have been created before I even used Postfixadmin.

If Postfix clearly does not require such an alias for a mailbox, why does Postfixadmin?

**Comment by gnanet** [comment]
In my experience soon after you allow your users to configure their email forwardings, the importance of having "default alias to self" will be clear ;)

But to detail the WHY:
To prevent accidental mail loss for users who are using any kind of "self service", that allows them to configure email forwarding, it is wise to set a default alias for every mailbox pointing to itself. 

In case the user makes a mistake, by setting up an alias with a a non-existent/mistyped email, or any destination that would cause messages to vanish, the default self-alias would store the message in the mailbox, and mail does not get lost.

**Comment by jsfan** [comment]
Fair enough. In that case, I would suggest that postfixadmin should not give this enigmatic error message but point out the requirement for an alias for every mailbox. As the original issue should make sufficiently clear, the error message as it is shown to the user at the moment is almost impossible to make sense of.

**Comment by cboltz** [comment]
The most important reasons for the mailbox aliases is to avoid problems if you have a catchall alias. Without the mailbox alias, the catchall would "win" so even mails addressed to the mailbox would go to the catchall target instead.

I know that the error message isn't too helpful, but from a PostfixAdmin POV, this is a "should never happen" case - if you create a mailbox with PostfixAdmin, the alias will also be created. Nevertheless, patches to improve the error handling are of course welcome ;-)

**Comment by gnanet** [comment]
I want to note: 
 - The title of this issue does not reflect the problem, because (according to the result of the  discussion) the validation regex-es are working as expected.
 - Second, database content, that is created prior postfixadmin was installed, may contain faulty, or incomplete settings, and this could trigger error messages, that may not point into the right direction.

Sounds simple to have an addition to the error message "This alias does not exist!" that describes the problem better  "The mailbox <emailaddress> is expected to have at least an alias to itself." but looking at the code it may be not as trivial as i think.

**Comment by jsfan** [comment]
@gnanet I agree that this has diverged from the original issue. I kind of hijacked it because of the error message. I agree that a database which is not in the correct state to begin with does not need to be handled by Postfixadmin. However, as we have already established the configuration I had was not really wrong even if it wasn't best practice.

I actually hacked the alias check out of my install to make everything work for the time being. If I can spare a minute, I will go back and see if I can just improve the error message there.

**Comment by gnanet** [comment]
Because of the fact, that it would require a complete team to create a "correct every possible database error" solution, i opt to simply making messages more meaningful. 

The thread itself changed topic because  @jsknto raised an issue which @jsfan debuggeg down to the causes well enough to find a part of postfixadmin that can be made even better. Thats a great thing.

I just noted, that maybe the original issue could be marked done, and the knowledge resulting from this issue could be used to start a new issue, so people facing similar can find it more quicker.

BUT its just my 2 cnts ;)

Sun is shining, so lets get off the monitors, and out to the nature. Happy weekend !

**Comment by peczgy** [comment]
You can't edit the mailbox if you don't have the user in the alias table. (It's missed during an update years ago)
I had to insert the data and choosed this solution. Now it's working for the mailbox administrators.

INSERT INTO alias (address, goto, domain, created, modified, active) SELECT mailbox.username, mailbox.username, mailbox.domain, NOW(), NOW(), mailbox.active, address FROM mailbox LEFT JOIN alias ON alias.address=mailbox.username WHERE address IS NULL
